baseURL = "https://wwang-yi-lin.github.io/site/"
languageCode = "en-us"
title = "My Hugo Site"
theme = "KeepIt"

[params]
  author = "Your Name"
  description = "A description of your site."

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
